package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"

	"github.com/n9te9/federation-gateway/_example/ec/inventory/graph/model"
)

// Inventories is the resolver for the inventories field.
func (r *queryResolver) Inventories(ctx context.Context) ([]*model.Product, error) {
	panic(fmt.Errorf("not implemented: Inventories - inventories"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	return []*model.Product{
		{
			Upc:    "1",
			Width:  ptr(30.0),
			Height: ptr(10.0),
		},
		{
			Upc: "2",
		},
	}
}
*/
